[package]
authors = ["Tamaki Mizuha <mizyoukan@outlook.com>"]
name = "heroku-rust-pg-test"
version = "0.1.0"
[dependencies]
error-chain = "0.11.0"
hyper = "0.11.9"
openssl = "0.9.23"

[dependencies.postgres]
features = ["with-openssl"]
version = "0.15.1"
