[package]
authors = ["Tamaki Mizuha <mizyoukan@outlook.com>"]
name = "heroku-rust-pg-test"
version = "0.1.0"
[dependencies]
error-chain = "0.11.0"
hyper = "0.11.9"
native-tls = "0.1.4"

[dependencies.postgres]
features = ["with-native-tls"]
version = "0.15.1"
